name: "Infrastructure Workflow"

# This workflow only triggers when code is pushed to a branch called infrastructure/*

# Activate when workflow is working
#on:
#  push:
#    paths:
#      - ".infrastructure/**"

on:
  push:
    branches: main

defaults:
    run:
      shell: bash
      working-directory: .infrastructure

jobs:
  #########################################################################
  # Workflow job to initialize, format, validate and check Terraform code #
  #########################################################################
  terraform-nonprod-preplan:
    runs-on: ubuntu-latest
    environment: NonProduction
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init

      - name: Terraform format
        run: terraform fmt -check --recursive

      - name: Terraform Validate
        run: terraform validate

  ##############################################################
  # Terraform plan job that uploads a terraform plan artifact  #
  ##############################################################
  terraform-nonprod-plan:
    needs: [terraform-nonprod-preplan]
    runs-on: ubuntu-latest
    environment: NonProduction
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -no-color -out=terraform.plan

      - name: Upload Terraform artifacts after successful plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform
          path: |
            .terraform
            *.tf
            *.lock.hcl
            terraform.plan
          if-no-files-found: error

  ##################################################################
  # Terraform apply job that downloads said artifact and applys it #
  ##################################################################
  terraform-nonprod-apply:
    needs: [terraform-nonprod-plan]
    runs-on: ubuntu-latest
    environment: NonProduction
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Get prepared plan
        uses: actions/download-artifact@v2
        with:
          name: terraform
      - run: chmod -R u+x .terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform apply
        run: terraform apply -auto-approve ./terraform.plan
