name: "Open Policy Agent Workflow"

# This workflow only triggers when code is pushed to a branch called test/*.
# Activate when OPA rules works.
on:
  push:
    branches: "test/*"

defaults:
    run:
      shell: bash
      
jobs:
  terraform-preplan:
    runs-on: ubuntu-latest
    environment: NonProduction
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
        working-directory: .infrastructure
      - name: Terraform format
        run: terraform fmt -check --recursive
        working-directory: .infrastructure
      - name: Terraform Validate
        run: terraform validate
        working-directory: .infrastructure

  run-opa-tests:
    needs: terraform-plan
    runs-on: ubuntu-latest 
    environment: NonProduction

    steps:
    - name: Checkout repository
      uses: actions/download-artifact@v2
    
    - name: Get Terraform Plan
      run: terraform plan --out terraform.plan
      working-directory: .infrastructure
    
    - name: Convert Terraform Plan to JSON
      run: terraform show -json terraform.plan > ../tfplan.json
      working-directory: .infrastructure
    
    - name: Show JSON Terraform plan
      run: cat tfplan.json
    
    # Maybe not necessary
    #- name: Login to Dockerhub
    #  uses: docker/login-action@v1
    #    with:
    #      username: ${{ secrets.DOCKER_HUB_USERNAME }}
    #      password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
     
    
    #- name: Install Open Policy Agent
      # Remember to use working-directory .infrastructure
      # Download and run OPA docker image

